[project]
name = "cogoff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-auth>=2.49.2",
    "google-genai>=1.73.1",
    "gspread>=6.2.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "python-dotenv>=1.2.2",
    "tenacity>=9.1.4",
]
